# Generated by Django 5.0 on 2024-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.CharField(
                        choices=[
                            ("amrc", "AMRC"),
                            ("amrc_jr", "AMRC Jr"),
                            ("amag", "AMAG"),
                            ("amag_jr", "AMAG Jr"),
                            ("amo2", "AMO2"),
                            ("kasaporov", "Kasaporov"),
                            ("inquiry", "Inquiry"),
                            ("anachronism", "Anachronism"),
                            ("brics", "Brics"),
                            ("gymrats", "Gym Rats"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("about_text", models.TextField()),
            ],
        ),
    ]
