# Generated by Django 5.0 on 2024-09-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_clubabout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="club_photos/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="website.clubabout",
                    ),
                ),
            ],
        ),
    ]
