# Generated by Django 5.0 on 2024-09-21 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_clubphoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubphoto",
            name="caption",
        ),
    ]
