# Generated by Django 5.0 on 2024-10-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_clubphoto_caption"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "club",
                    models.CharField(
                        choices=[
                            ("amrc", "AMRC"),
                            ("amrc_jr", "AMRC Jr"),
                            ("amo2", "AMO2"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(upload_to="books/")),
            ],
        ),
    ]
