# Generated by Django 5.0 on 2024-10-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="club",
            field=models.CharField(
                choices=[("amrc", "AMRC"), ("amrc_jr", "AMRC Jr"), ("amo2", "AMO2")],
                max_length=20,
            ),
        ),
    ]
