# Generated by Django 5.0 on 2024-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_book_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubabout",
            name="logo",
            field=models.ImageField(blank=True, upload_to="club_logos/"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="branch",
            field=models.CharField(
                choices=[
                    ("def", "Default"),
                    ("amb", "Barsha"),
                    ("amg", "Garhoud"),
                    ("amk", "Khawaneej"),
                ],
                default="def",
                max_length=3,
            ),
        ),
    ]
