# Generated by Django 5.0.6 on 2024-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_clubabout_logo_teammember_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubabout',
            name='club',
            field=models.CharField(choices=[('amrc', 'AMRC'), ('amrc_jr', 'AMRC Jr'), ('amag', 'AMAG'), ('amag_jr', 'AMAG Jr'), ('amo2', 'AMO2'), ('kasparov', 'Kasparov'), ('inquiry', 'Inquiry'), ('anachronism', 'Anachronism'), ('brics', 'Brics'), ('gymrats', 'Gym Rats')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='club',
            field=models.CharField(choices=[('amrc', 'AMRC'), ('amrc_jr', 'AMRC Jr'), ('amag', 'AMAG'), ('amag_jr', 'AMAG Jr'), ('amo2', 'AMO2'), ('kasparov', 'Kasparov'), ('inquiry', 'Inquiry'), ('anachronism', 'Anachronism')], max_length=20),
        ),
    ]
